server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: id-catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog-service/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    gateway:
      enable: true
  endpoints:
    web:
      exposure:
        include: gateway

